<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.9.36">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="">
<meta name="dcterms.date" content="2026-07-04">

<title>Proyecto de Regresión Lineal Múltiple</title>
<style>
/* Default styles provided by pandoc.
** See https://pandoc.org/MANUAL.html#variables-for-html for config info.
*/
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
html { -webkit-text-size-adjust: 100%; }
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="borrador_correcciones_corregido (8)_files/libs/clipboard/clipboard.min.js"></script>
<script src="borrador_correcciones_corregido (8)_files/libs/quarto-html/quarto.js" type="module"></script>
<script src="borrador_correcciones_corregido (8)_files/libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="borrador_correcciones_corregido (8)_files/libs/quarto-html/popper.min.js"></script>
<script src="borrador_correcciones_corregido (8)_files/libs/quarto-html/tippy.umd.min.js"></script>
<script src="borrador_correcciones_corregido (8)_files/libs/quarto-html/anchor.min.js"></script>
<link href="borrador_correcciones_corregido (8)_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="borrador_correcciones_corregido (8)_files/libs/quarto-html/quarto-syntax-highlighting-845c23b38eaddc0f92fda52bfe77a8c8.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="borrador_correcciones_corregido (8)_files/libs/bootstrap/bootstrap.min.js"></script>
<link href="borrador_correcciones_corregido (8)_files/libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="borrador_correcciones_corregido (8)_files/libs/bootstrap/bootstrap-efbb37e9afcc02144ebbc7afd12a776f.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">

  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script defer="" src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN" && texText && texText.data) {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

</head>

<body class="quarto-light">

<div id="quarto-content" class="page-columns page-rows-contents page-layout-article">
<div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
  <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Table of contents</h2>
   
  <ul>
  <li><a href="#enunciado-del-proyecto" id="toc-enunciado-del-proyecto" class="nav-link active" data-scroll-target="#enunciado-del-proyecto"><span class="header-section-number">1</span> Enunciado del proyecto</a></li>
  <li><a href="#introducción" id="toc-introducción" class="nav-link" data-scroll-target="#introducción"><span class="header-section-number">2</span> Introducción</a>
  <ul class="collapse">
  <li><a href="#relevancia" id="toc-relevancia" class="nav-link" data-scroll-target="#relevancia"><span class="header-section-number">2.1</span> Relevancia</a></li>
  <li><a href="#variables-seleccionadas" id="toc-variables-seleccionadas" class="nav-link" data-scroll-target="#variables-seleccionadas"><span class="header-section-number">2.2</span> Variables seleccionadas</a>
  <ul class="collapse">
  <li><a href="#descripción-detallada-de-las-variables" id="toc-descripción-detallada-de-las-variables" class="nav-link" data-scroll-target="#descripción-detallada-de-las-variables"><span class="header-section-number">2.2.1</span> Descripción detallada de las variables</a></li>
  <li><a href="#verificación-independencia-entre-la-variable-respuesta-y-las-covariables" id="toc-verificación-independencia-entre-la-variable-respuesta-y-las-covariables" class="nav-link" data-scroll-target="#verificación-independencia-entre-la-variable-respuesta-y-las-covariables"><span class="header-section-number">2.2.2</span> Verificación: independencia entre la variable respuesta y las covariables</a></li>
  </ul></li>
  <li><a href="#objetivo" id="toc-objetivo" class="nav-link" data-scroll-target="#objetivo"><span class="header-section-number">2.3</span> Objetivo</a></li>
  <li><a href="#hipótesis" id="toc-hipótesis" class="nav-link" data-scroll-target="#hipótesis"><span class="header-section-number">2.4</span> Hipótesis</a></li>
  </ul></li>
  <li><a href="#análisis-descriptivo" id="toc-análisis-descriptivo" class="nav-link" data-scroll-target="#análisis-descriptivo"><span class="header-section-number">3</span> Análisis descriptivo</a>
  <ul class="collapse">
  <li><a href="#información-sobre-la-base-de-datos" id="toc-información-sobre-la-base-de-datos" class="nav-link" data-scroll-target="#información-sobre-la-base-de-datos"><span class="header-section-number">3.1</span> Información sobre la base de datos</a></li>
  <li><a href="#selección-de-la-muestra" id="toc-selección-de-la-muestra" class="nav-link" data-scroll-target="#selección-de-la-muestra"><span class="header-section-number">3.2</span> Selección de la muestra</a></li>
  <li><a href="#base-consolidada" id="toc-base-consolidada" class="nav-link" data-scroll-target="#base-consolidada"><span class="header-section-number">3.3</span> Base consolidada</a></li>
  <li><a href="#variable-respuesta-logaritmo-del-ingreso-laboral-mensual" id="toc-variable-respuesta-logaritmo-del-ingreso-laboral-mensual" class="nav-link" data-scroll-target="#variable-respuesta-logaritmo-del-ingreso-laboral-mensual"><span class="header-section-number">3.4</span> Variable respuesta: logaritmo del ingreso laboral mensual</a></li>
  <li><a href="#descripción-de-las-covariables-continuas" id="toc-descripción-de-las-covariables-continuas" class="nav-link" data-scroll-target="#descripción-de-las-covariables-continuas"><span class="header-section-number">3.5</span> Descripción de las covariables continuas</a></li>
  <li><a href="#descripción-de-las-variables-categóricas" id="toc-descripción-de-las-variables-categóricas" class="nav-link" data-scroll-target="#descripción-de-las-variables-categóricas"><span class="header-section-number">3.6</span> Descripción de las variables categóricas</a>
  <ul class="collapse">
  <li><a href="#posición-ocupacional" id="toc-posición-ocupacional" class="nav-link" data-scroll-target="#posición-ocupacional"><span class="header-section-number">3.6.1</span> Posición ocupacional</a></li>
  <li><a href="#rama-de-actividad-económica" id="toc-rama-de-actividad-económica" class="nav-link" data-scroll-target="#rama-de-actividad-económica"><span class="header-section-number">3.6.2</span> Rama de actividad económica</a></li>
  </ul></li>
  </ul></li>
  <li><a href="#modelo-matemático-propuesto" id="toc-modelo-matemático-propuesto" class="nav-link" data-scroll-target="#modelo-matemático-propuesto"><span class="header-section-number">4</span> Modelo matemático propuesto</a></li>
  <li><a href="#conclusiones" id="toc-conclusiones" class="nav-link" data-scroll-target="#conclusiones"><span class="header-section-number">5</span> Conclusiones</a></li>
  <li><a href="#referencias" id="toc-referencias" class="nav-link" data-scroll-target="#referencias"><span class="header-section-number">6</span> Referencias</a></li>
  </ul>
</nav>
</div>
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Proyecto de Regresión Lineal Múltiple</h1>
<p class="subtitle lead">Determinantes del ingreso laboral mensual en Colombia</p>
</div>



<div class="quarto-title-meta">

    
    <div>
    <div class="quarto-title-meta-heading">Published</div>
    <div class="quarto-title-meta-contents">
      <p class="date">July 4, 2026</p>
    </div>
  </div>
  
    
  </div>
  


</header>


<section id="enunciado-del-proyecto" class="level1" data-number="1">
<h1 data-number="1"><span class="header-section-number">1</span> Enunciado del proyecto</h1>
<p>El proyecto consiste en buscar una base de datos con datos colombianos que contenga una variable de respuesta continua (<span class="math inline">\(Y\)</span>), al menos cinco covariables continuas (<span class="math inline">\(X\)</span>) y una variable categórica (<span class="math inline">\(Z\)</span>) con al menos tres categorías. Los análisis se realizan con máximo 100 registros. El proyecto tiene tres entregas y una exposición final.</p>
<ol type="1">
<li>Contextualizar el fenómeno a modelar: explicar el significado de la variable de respuesta y las covariables, la relevancia del estudio y su objetivo. Establecer dos hipótesis que se desean probar con el modelo.</li>
<li>Realizar un análisis descriptivo exhaustivo y pertinente para el tipo de modelo que se va a aplicar.</li>
</ol>
</section>
<section id="introducción" class="level1" data-number="2">
<h1 data-number="2"><span class="header-section-number">2</span> Introducción</h1>
<p>El ingreso laboral es uno de los principales determinantes del bienestar de los hogares colombianos y uno de los indicadores más utilizados para analizar la desigualdad económica del país. Explicar por qué unos trabajadores ganan más que otros es una pregunta central de la economía laboral, y la respuesta habitual —propuesta por Mincer (1974)— es que el ingreso depende principalmente de la acumulación de capital humano (educación y experiencia), de la intensidad con que se trabaja (horas) y de las características del empleo (tipo de vinculación y sector económico).</p>
<p>En Colombia, donde la informalidad laboral y la heterogeneidad sectorial son altas, estos factores no siempre se traducen en el mismo nivel de ingreso: dos personas con la misma escolaridad pueden percibir remuneraciones muy distintas según su posición ocupacional o la rama de actividad en la que trabajan. Este proyecto busca cuantificar, a partir de microdatos de la Gran Encuesta Integrada de Hogares (GEIH), qué tanto explican estas variables la variabilidad del ingreso laboral mensual.</p>
<section id="relevancia" class="level2" data-number="2.1">
<h2 data-number="2.1" class="anchored" data-anchor-id="relevancia"><span class="header-section-number">2.1</span> Relevancia</h2>
<p>Comprender los determinantes del ingreso laboral es relevante tanto desde la perspectiva académica como de política pública. Desde la teoría del capital humano, permite contrastar empíricamente si la educación y la experiencia se traducen efectivamente en mayores retornos salariales en el mercado colombiano. Desde la política pública, identificar qué variables —además de la educación— están asociadas a mayores o menores ingresos (posición ocupacional, sector económico, antigüedad) aporta evidencia útil para el diseño de políticas de formalización laboral, empleo y reducción de brechas salariales.</p>
</section>
<section id="variables-seleccionadas" class="level2" data-number="2.2">
<h2 data-number="2.2" class="anchored" data-anchor-id="variables-seleccionadas"><span class="header-section-number">2.2</span> Variables seleccionadas</h2>
<div class="cell">
<div class="cell-output-display">
<table class="caption-top table table-sm table-striped small">
<caption>Variables seleccionadas, rol en el modelo y significado en el estudio.</caption>
<colgroup>
<col style="width: 19%">
<col style="width: 17%">
<col style="width: 4%">
<col style="width: 5%">
<col style="width: 53%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">Nombre</th>
<th style="text-align: left;">Codigo</th>
<th style="text-align: left;">Rol</th>
<th style="text-align: left;">Tipo</th>
<th style="text-align: left;">Significado</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Logaritmo del ingreso laboral mensual</td>
<td style="text-align: left;">INGLABO (transformada)</td>
<td style="text-align: left;">Y</td>
<td style="text-align: left;">Continua</td>
<td style="text-align: left;">Ingreso laboral mensual transformado a escala logarítmica para reducir la asimetría de la distribución.</td>
</tr>
<tr class="even">
<td style="text-align: left;">Horas trabajadas por semana</td>
<td style="text-align: left;">P6800</td>
<td style="text-align: left;">X1</td>
<td style="text-align: left;">Continua</td>
<td style="text-align: left;">Intensidad del trabajo desarrollado durante la semana de referencia.</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Años de escolaridad</td>
<td style="text-align: left;">P3042 / P3042S1 (derivada)</td>
<td style="text-align: left;">X2</td>
<td style="text-align: left;">Continua</td>
<td style="text-align: left;">Años de educación formal aprobados; mide la acumulación de capital humano.</td>
</tr>
<tr class="even">
<td style="text-align: left;">Experiencia potencial</td>
<td style="text-align: left;">P6040, P3042, P3042S1 (derivada)</td>
<td style="text-align: left;">X3</td>
<td style="text-align: left;">Continua</td>
<td style="text-align: left;">Edad - escolaridad - 6; aproxima los años potenciales de experiencia laboral.</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Experiencia potencial al cuadrado</td>
<td style="text-align: left;">Derivada de X3</td>
<td style="text-align: left;">X4</td>
<td style="text-align: left;">Continua</td>
<td style="text-align: left;">Captura el efecto no lineal (rendimientos decrecientes) de la experiencia sobre el ingreso.</td>
</tr>
<tr class="even">
<td style="text-align: left;">Antigüedad en el empleo actual</td>
<td style="text-align: left;">P6426</td>
<td style="text-align: left;">X6</td>
<td style="text-align: left;">Continua</td>
<td style="text-align: left;">Meses en el empleo u ocupación actual; aproxima estabilidad y experiencia específica.</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Posición ocupacional</td>
<td style="text-align: left;">P6430</td>
<td style="text-align: left;">X5 (Z1)</td>
<td style="text-align: left;">Categórica</td>
<td style="text-align: left;">Forma de vinculación laboral (empleado particular, del gobierno, cuenta propia, etc.).</td>
</tr>
<tr class="even">
<td style="text-align: left;">Rama de actividad económica</td>
<td style="text-align: left;">RAMA2D_R4</td>
<td style="text-align: left;">X7 (Z2)</td>
<td style="text-align: left;">Categórica</td>
<td style="text-align: left;">Sector económico (CIIU, 2 dígitos) en el que se desempeña el trabajador.</td>
</tr>
</tbody>
</table>
</div>
</div>
<section id="descripción-detallada-de-las-variables" class="level3" data-number="2.2.1">
<h3 data-number="2.2.1" class="anchored" data-anchor-id="descripción-detallada-de-las-variables"><span class="header-section-number">2.2.1</span> Descripción detallada de las variables</h3>
<p><strong>Y: Logaritmo del ingreso laboral mensual.</strong> La variable de respuesta corresponde al ingreso laboral mensual percibido por las personas ocupadas incluidas en la GEIH, expresado en pesos colombianos. Dado que en economía laboral es ampliamente reconocido que la distribución de los ingresos presenta una marcada asimetría positiva, la variable dependiente se transforma mediante el logaritmo natural, lo que reduce la asimetría, disminuye la influencia de valores extremos y permite interpretar los coeficientes del modelo como variaciones porcentuales aproximadas del ingreso (especificación clásica de Mincer, 1974).</p>
<p><strong>X1: Horas trabajadas por semana.</strong> Número de horas que la persona trabajó habitualmente durante la semana de referencia en su ocupación principal. Se espera una relación positiva con el ingreso.</p>
<p><strong>X2: Años de escolaridad.</strong> Construida a partir del nivel educativo alcanzado (P3042) y el último grado aprobado dentro de ese nivel (P3042S1), siguiendo la convención estándar de conversión a años acumulados de educación usada en estudios de mercado laboral con la GEIH.</p>
<p><strong>X3: Experiencia potencial.</strong> Se calcula como <span class="math inline">\(\text{Edad} - \text{Escolaridad} - 6\)</span>, asumiendo que las personas ingresan al sistema educativo aproximadamente a los seis años y comienzan su vida laboral al finalizar su formación.</p>
<p><strong>X4: Experiencia potencial al cuadrado.</strong> Incorpora la relación cóncava entre experiencia e ingreso: los ingresos aumentan con la experiencia, pero a una tasa decreciente.</p>
<p><strong>X5 (Z1): Posición ocupacional.</strong> Forma de vinculación del trabajador con el mercado laboral (empleado particular, empleado del gobierno, cuenta propia, patrón, empleado doméstico, etc.). Variable categórica incorporada mediante variables dummy.</p>
<p><strong>X6: Antigüedad en el empleo actual.</strong> Meses que el trabajador lleva en su empleo u ocupación actual; aproxima estabilidad laboral y experiencia específica en la organización.</p>
<p><strong>X7 (Z2): Rama de actividad económica.</strong> Sector económico en el que se desempeña el trabajador, agrupado según la Clasificación Industrial Internacional Uniforme (CIIU) a 2 dígitos.</p>
</section>
<section id="verificación-independencia-entre-la-variable-respuesta-y-las-covariables" class="level3" data-number="2.2.2">
<h3 data-number="2.2.2" class="anchored" data-anchor-id="verificación-independencia-entre-la-variable-respuesta-y-las-covariables"><span class="header-section-number">2.2.2</span> Verificación: independencia entre la variable respuesta y las covariables</h3>
<p>Antes de fijar el conjunto de covariables se verificó que ninguna de ellas sea, por construcción, un componente algebraico de la variable de respuesta. El ingreso laboral mensual (<code>inglabo</code>) es un campo <strong>reportado directamente por el encuestado</strong> en la GEIH —no una suma ni un producto de otras variables de la encuesta calculado por nosotros—, por lo que <span class="math inline">\(Y=\ln(\text{inglabo})\)</span> no se construye a partir de <span class="math inline">\(X_1,\dots,X_7\)</span>. En particular:</p>
<ul>
<li><span class="math inline">\(Y\)</span> <strong>no</strong> es igual a horas × tarifa horaria, ni a la suma de sus componentes; el DANE la recoge como una única pregunta de ingreso total.</li>
<li>La escolaridad (<span class="math inline">\(X_2\)</span>) y la experiencia potencial (<span class="math inline">\(X_3\)</span>) se derivan de variables demográficas y educativas (<code>p3042</code>, <code>p3042s1</code>, <code>p6040</code>), <strong>no del ingreso</strong>, por lo que tampoco intervienen en la construcción de <span class="math inline">\(Y\)</span>.</li>
<li>El resto de covariables (<span class="math inline">\(X_1\)</span> horas, <span class="math inline">\(X_5\)</span> posición, <span class="math inline">\(X_6\)</span> antigüedad, <span class="math inline">\(X_7\)</span> rama) provienen de preguntas independientes del módulo de ocupados y no participan en el cálculo de <code>inglabo</code>.</li>
</ul>
<p>Esto garantiza que la relación entre <span class="math inline">\(Y\)</span> y cada <span class="math inline">\(X\)</span> que se explora en el análisis descriptivo (y que luego se modelará) es una asociación empírica a estimar, y no una identidad matemática impuesta por la propia definición de las variables.</p>
</section>
</section>
<section id="objetivo" class="level2" data-number="2.3">
<h2 data-number="2.3" class="anchored" data-anchor-id="objetivo"><span class="header-section-number">2.3</span> Objetivo</h2>
<p>Determinar qué características individuales (educación, experiencia), laborales (horas, antigüedad, posición ocupacional) y sectoriales (rama de actividad) explican el logaritmo del ingreso laboral mensual de los trabajadores colombianos, con el fin de aportar evidencia sobre los principales determinantes del ingreso en el mercado laboral del país.</p>
</section>
<section id="hipótesis" class="level2" data-number="2.4">
<h2 data-number="2.4" class="anchored" data-anchor-id="hipótesis"><span class="header-section-number">2.4</span> Hipótesis</h2>
<p>Las siguientes hipótesis se desprenden directamente de la contextualización presentada en la Introducción y la Relevancia (teoría del capital humano de Mincer, 1974, y la heterogeneidad del mercado laboral colombiano). Cada una se plantea de forma que pueda traducirse, en la etapa de modelación, en el signo y la significancia esperados de parámetros específicos del modelo <span class="math inline">\(\ln(Y_i)=\beta_0+\beta_1X_{1i}+\dots+\beta_7X_{7i}+\varepsilon_i\)</span>.</p>
<p><strong>Hipótesis 1: la escolaridad y la experiencia potencial explican una parte sustancial de la variabilidad del ingreso laboral.</strong> De acuerdo con la teoría del capital humano, se espera que los trabajadores con mayor escolaridad y mayor experiencia potencial —hasta el punto en que los rendimientos empiezan a decrecer— perciban ingresos más altos. En términos del modelo, esta hipótesis se traduce en <span class="math inline">\(\beta_2&gt;0\)</span> (escolaridad), <span class="math inline">\(\beta_3&gt;0\)</span> (experiencia) y <span class="math inline">\(\beta_4&lt;0\)</span> (experiencia al cuadrado), reflejando el perfil cóncavo típico de la ecuación de Mincer; se espera además que ambos coeficientes sean estadísticamente significativos.</p>
<p><strong>Hipótesis 2: la posición ocupacional y la rama de actividad económica generan diferencias sistemáticas en el ingreso, incluso después de considerar la escolaridad y la experiencia.</strong> Dada la heterogeneidad e informalidad del mercado laboral colombiano descrita en la Relevancia, se espera que existan brechas de ingreso entre categorías ocupacionales y sectoriales que la educación y la experiencia por sí solas no logran explicar. En el modelo, esto se traduce en que al menos algunos de los coeficientes asociados a las variables dummy de posición ocupacional (<span class="math inline">\(\beta_5\)</span>) y de rama de actividad (<span class="math inline">\(\beta_7\)</span>) —tomando como referencia “Empleado particular”— sean estadísticamente significativos y distintos de cero.</p>
</section>
</section>
<section id="análisis-descriptivo" class="level1" data-number="3">
<h1 data-number="3"><span class="header-section-number">3</span> Análisis descriptivo</h1>
<section id="información-sobre-la-base-de-datos" class="level2" data-number="3.1">
<h2 data-number="3.1" class="anchored" data-anchor-id="información-sobre-la-base-de-datos"><span class="header-section-number">3.1</span> Información sobre la base de datos</h2>
<p>La base de datos utilizada corresponde a la Gran Encuesta Integrada de Hogares (GEIH), operativo de enero de 2024, publicada por el Departamento Administrativo Nacional de Estadística (DANE). Se utilizan dos de sus módulos:</p>
<ul>
<li><strong>Ocupados</strong>: contiene las variables laborales de las personas ocupadas (ingreso, horas trabajadas, posición ocupacional, antigüedad, rama de actividad, entre otras).</li>
<li><strong>Características generales, seguridad social en salud y educación</strong>: contiene las variables demográficas y educativas (edad, nivel educativo, grado aprobado).</li>
</ul>
<p>Ambos módulos se identifican a nivel de persona mediante las llaves <code>directorio</code>, <code>secuencia_p</code> y <code>orden</code>, por lo que se unen (<code>left_join</code>) usando esa combinación.</p>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a>paquetes <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="st">"dplyr"</span>, <span class="st">"car"</span>, <span class="st">"ggplot2"</span>, <span class="st">"corrplot"</span>, <span class="st">"readr"</span>, <span class="st">"tidyr"</span>, <span class="st">"stringr"</span>, <span class="st">"knitr"</span>)</span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a>instalar <span class="ot">&lt;-</span> paquetes[<span class="sc">!</span>(paquetes <span class="sc">%in%</span> <span class="fu">installed.packages</span>()[, <span class="st">"Package"</span>])]</span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a><span class="cf">if</span> (<span class="fu">length</span>(instalar)) <span class="fu">install.packages</span>(instalar)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
</div>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb2"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(dplyr)</span>
<span id="cb2-2"><a href="#cb2-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(readr)</span>
<span id="cb2-3"><a href="#cb2-3" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(ggplot2)</span>
<span id="cb2-4"><a href="#cb2-4" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(car)</span>
<span id="cb2-5"><a href="#cb2-5" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(corrplot)</span>
<span id="cb2-6"><a href="#cb2-6" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tidyr)</span>
<span id="cb2-7"><a href="#cb2-7" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(stringr)</span>
<span id="cb2-8"><a href="#cb2-8" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(knitr)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
</div>
<p>Quarto usa como directorio de trabajo la carpeta donde está guardado este archivo <code>.qmd</code>. Ajusta <code>ruta_datos</code> según dónde tengas los archivos <code>.CSV</code> de la GEIH. <strong>Verifica el nombre exacto de la carpeta en tu explorador de archivos</strong> (mayúsculas, guiones y guiones bajos deben coincidir exactamente):</p>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb3"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a><span class="co"># OJO: el nombre debe coincidir EXACTAMENTE con el de la carpeta en Windows,</span></span>
<span id="cb3-2"><a href="#cb3-2" aria-hidden="true" tabindex="-1"></a><span class="co"># incluyendo mayúsculas/minúsculas y el guion "-main" (no guion bajo "_main").</span></span>
<span id="cb3-3"><a href="#cb3-3" aria-hidden="true" tabindex="-1"></a>ruta_datos <span class="ot">&lt;-</span> <span class="st">"C:/Users/Daniela/Downloads/ModeloSalariosColombianos-main"</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
</div>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb4"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a>ocupados <span class="ot">&lt;-</span> <span class="fu">read_csv2</span>(</span>
<span id="cb4-2"><a href="#cb4-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">file.path</span>(ruta_datos, <span class="st">"Ocupados.CSV"</span>),</span>
<span id="cb4-3"><a href="#cb4-3" aria-hidden="true" tabindex="-1"></a>  <span class="at">show_col_types =</span> <span class="cn">FALSE</span></span>
<span id="cb4-4"><a href="#cb4-4" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb4-5"><a href="#cb4-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb4-6"><a href="#cb4-6" aria-hidden="true" tabindex="-1"></a>caracteristicas <span class="ot">&lt;-</span> <span class="fu">read_csv2</span>(</span>
<span id="cb4-7"><a href="#cb4-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">file.path</span>(ruta_datos, <span class="st">"Características generales, seguridad social en salud y educación.CSV"</span>),</span>
<span id="cb4-8"><a href="#cb4-8" aria-hidden="true" tabindex="-1"></a>  <span class="at">show_col_types =</span> <span class="cn">FALSE</span></span>
<span id="cb4-9"><a href="#cb4-9" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb4-10"><a href="#cb4-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb4-11"><a href="#cb4-11" aria-hidden="true" tabindex="-1"></a><span class="fu">names</span>(ocupados) <span class="ot">&lt;-</span> <span class="fu">tolower</span>(<span class="fu">names</span>(ocupados))</span>
<span id="cb4-12"><a href="#cb4-12" aria-hidden="true" tabindex="-1"></a><span class="fu">names</span>(caracteristicas) <span class="ot">&lt;-</span> <span class="fu">tolower</span>(<span class="fu">names</span>(caracteristicas))</span>
<span id="cb4-13"><a href="#cb4-13" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb4-14"><a href="#cb4-14" aria-hidden="true" tabindex="-1"></a>llaves <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="st">"directorio"</span>, <span class="st">"secuencia_p"</span>, <span class="st">"orden"</span>)</span>
<span id="cb4-15"><a href="#cb4-15" aria-hidden="true" tabindex="-1"></a><span class="fu">stopifnot</span>(<span class="fu">all</span>(llaves <span class="sc">%in%</span> <span class="fu">names</span>(ocupados)))</span>
<span id="cb4-16"><a href="#cb4-16" aria-hidden="true" tabindex="-1"></a><span class="fu">stopifnot</span>(<span class="fu">all</span>(llaves <span class="sc">%in%</span> <span class="fu">names</span>(caracteristicas)))</span>
<span id="cb4-17"><a href="#cb4-17" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb4-18"><a href="#cb4-18" aria-hidden="true" tabindex="-1"></a>datos <span class="ot">&lt;-</span> ocupados <span class="sc">%&gt;%</span></span>
<span id="cb4-19"><a href="#cb4-19" aria-hidden="true" tabindex="-1"></a>  <span class="fu">left_join</span>(caracteristicas, <span class="at">by =</span> llaves, <span class="at">relationship =</span> <span class="st">"one-to-one"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
</div>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb5"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a><span class="co"># --- Escolaridad (años acumulados) ---------------------------------------</span></span>
<span id="cb5-2"><a href="#cb5-2" aria-hidden="true" tabindex="-1"></a>anios_previos <span class="ot">&lt;-</span> <span class="fu">c</span>(</span>
<span id="cb5-3"><a href="#cb5-3" aria-hidden="true" tabindex="-1"></a>  <span class="st">"1"</span> <span class="ot">=</span> <span class="dv">0</span>, <span class="st">"2"</span> <span class="ot">=</span> <span class="dv">0</span>, <span class="st">"3"</span> <span class="ot">=</span> <span class="dv">0</span>, <span class="st">"4"</span> <span class="ot">=</span> <span class="dv">5</span>, <span class="st">"5"</span> <span class="ot">=</span> <span class="dv">9</span>, <span class="st">"6"</span> <span class="ot">=</span> <span class="dv">9</span>, <span class="st">"7"</span> <span class="ot">=</span> <span class="dv">11</span>,</span>
<span id="cb5-4"><a href="#cb5-4" aria-hidden="true" tabindex="-1"></a>  <span class="st">"8"</span> <span class="ot">=</span> <span class="dv">11</span>, <span class="st">"9"</span> <span class="ot">=</span> <span class="dv">13</span>, <span class="st">"10"</span> <span class="ot">=</span> <span class="dv">16</span>, <span class="st">"11"</span> <span class="ot">=</span> <span class="dv">17</span>, <span class="st">"12"</span> <span class="ot">=</span> <span class="dv">19</span>, <span class="st">"13"</span> <span class="ot">=</span> <span class="dv">21</span></span>
<span id="cb5-5"><a href="#cb5-5" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb5-6"><a href="#cb5-6" aria-hidden="true" tabindex="-1"></a>niveles_semestres <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="st">"8"</span>, <span class="st">"9"</span>, <span class="st">"10"</span>, <span class="st">"11"</span>, <span class="st">"12"</span>, <span class="st">"13"</span>)</span>
<span id="cb5-7"><a href="#cb5-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-8"><a href="#cb5-8" aria-hidden="true" tabindex="-1"></a>datos <span class="ot">&lt;-</span> datos <span class="sc">%&gt;%</span></span>
<span id="cb5-9"><a href="#cb5-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(</span>
<span id="cb5-10"><a href="#cb5-10" aria-hidden="true" tabindex="-1"></a>    <span class="at">nivel_chr =</span> <span class="fu">as.character</span>(p3042),</span>
<span id="cb5-11"><a href="#cb5-11" aria-hidden="true" tabindex="-1"></a>    <span class="at">escolaridad =</span> anios_previos[nivel_chr] <span class="sc">+</span></span>
<span id="cb5-12"><a href="#cb5-12" aria-hidden="true" tabindex="-1"></a>      <span class="fu">ifelse</span>(nivel_chr <span class="sc">%in%</span> niveles_semestres,</span>
<span id="cb5-13"><a href="#cb5-13" aria-hidden="true" tabindex="-1"></a>             <span class="fu">coalesce</span>(p3042s1, <span class="dv">0</span>) <span class="sc">/</span> <span class="dv">2</span>,</span>
<span id="cb5-14"><a href="#cb5-14" aria-hidden="true" tabindex="-1"></a>             <span class="fu">coalesce</span>(p3042s1, <span class="dv">0</span>)),</span>
<span id="cb5-15"><a href="#cb5-15" aria-hidden="true" tabindex="-1"></a>    <span class="at">escolaridad =</span> <span class="fu">ifelse</span>(nivel_chr <span class="sc">%in%</span> <span class="fu">c</span>(<span class="st">"1"</span>, <span class="st">"2"</span>), <span class="dv">0</span>, escolaridad)</span>
<span id="cb5-16"><a href="#cb5-16" aria-hidden="true" tabindex="-1"></a>  )</span>
<span id="cb5-17"><a href="#cb5-17" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-18"><a href="#cb5-18" aria-hidden="true" tabindex="-1"></a><span class="co"># --- Experiencia potencial y su cuadrado ----------------------------------</span></span>
<span id="cb5-19"><a href="#cb5-19" aria-hidden="true" tabindex="-1"></a>datos <span class="ot">&lt;-</span> datos <span class="sc">%&gt;%</span></span>
<span id="cb5-20"><a href="#cb5-20" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(</span>
<span id="cb5-21"><a href="#cb5-21" aria-hidden="true" tabindex="-1"></a>    <span class="at">experiencia  =</span> <span class="fu">pmax</span>(p6040 <span class="sc">-</span> escolaridad <span class="sc">-</span> <span class="dv">6</span>, <span class="dv">0</span>),</span>
<span id="cb5-22"><a href="#cb5-22" aria-hidden="true" tabindex="-1"></a>    <span class="at">experiencia2 =</span> experiencia<span class="sc">^</span><span class="dv">2</span></span>
<span id="cb5-23"><a href="#cb5-23" aria-hidden="true" tabindex="-1"></a>  )</span>
<span id="cb5-24"><a href="#cb5-24" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-25"><a href="#cb5-25" aria-hidden="true" tabindex="-1"></a><span class="co"># --- Log del ingreso -------------------------------------------------------</span></span>
<span id="cb5-26"><a href="#cb5-26" aria-hidden="true" tabindex="-1"></a>datos <span class="ot">&lt;-</span> datos <span class="sc">%&gt;%</span></span>
<span id="cb5-27"><a href="#cb5-27" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(<span class="sc">!</span><span class="fu">is.na</span>(inglabo), inglabo <span class="sc">&gt;</span> <span class="dv">0</span>) <span class="sc">%&gt;%</span></span>
<span id="cb5-28"><a href="#cb5-28" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">ln_ingreso =</span> <span class="fu">log</span>(inglabo))</span>
<span id="cb5-29"><a href="#cb5-29" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-30"><a href="#cb5-30" aria-hidden="true" tabindex="-1"></a><span class="co"># --- Variables categóricas ---------------------------------------------</span></span>
<span id="cb5-31"><a href="#cb5-31" aria-hidden="true" tabindex="-1"></a>etiquetas_posicion <span class="ot">&lt;-</span> <span class="fu">c</span>(</span>
<span id="cb5-32"><a href="#cb5-32" aria-hidden="true" tabindex="-1"></a>  <span class="st">"1"</span> <span class="ot">=</span> <span class="st">"Empleado_particular"</span>, <span class="st">"2"</span> <span class="ot">=</span> <span class="st">"Empleado_gobierno"</span>,</span>
<span id="cb5-33"><a href="#cb5-33" aria-hidden="true" tabindex="-1"></a>  <span class="st">"3"</span> <span class="ot">=</span> <span class="st">"Empleado_domestico"</span>,  <span class="st">"4"</span> <span class="ot">=</span> <span class="st">"Cuenta_propia"</span>,</span>
<span id="cb5-34"><a href="#cb5-34" aria-hidden="true" tabindex="-1"></a>  <span class="st">"5"</span> <span class="ot">=</span> <span class="st">"Patron_empleador"</span>,    <span class="st">"6"</span> <span class="ot">=</span> <span class="st">"Trab_familiar_sin_remun"</span>,</span>
<span id="cb5-35"><a href="#cb5-35" aria-hidden="true" tabindex="-1"></a>  <span class="st">"7"</span> <span class="ot">=</span> <span class="st">"Trab_sin_remun_otros_hogares"</span>, <span class="st">"8"</span> <span class="ot">=</span> <span class="st">"Jornalero_peon"</span>,</span>
<span id="cb5-36"><a href="#cb5-36" aria-hidden="true" tabindex="-1"></a>  <span class="st">"9"</span> <span class="ot">=</span> <span class="st">"Otro"</span></span>
<span id="cb5-37"><a href="#cb5-37" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb5-38"><a href="#cb5-38" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-39"><a href="#cb5-39" aria-hidden="true" tabindex="-1"></a>datos <span class="ot">&lt;-</span> datos <span class="sc">%&gt;%</span></span>
<span id="cb5-40"><a href="#cb5-40" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(</span>
<span id="cb5-41"><a href="#cb5-41" aria-hidden="true" tabindex="-1"></a>    <span class="at">posicion =</span> <span class="fu">factor</span>(etiquetas_posicion[<span class="fu">as.character</span>(p6430)]),</span>
<span id="cb5-42"><a href="#cb5-42" aria-hidden="true" tabindex="-1"></a>    <span class="at">rama     =</span> <span class="fu">factor</span>(rama2d_r4)</span>
<span id="cb5-43"><a href="#cb5-43" aria-hidden="true" tabindex="-1"></a>  )</span>
<span id="cb5-44"><a href="#cb5-44" aria-hidden="true" tabindex="-1"></a>datos<span class="sc">$</span>posicion <span class="ot">&lt;-</span> <span class="fu">relevel</span>(datos<span class="sc">$</span>posicion, <span class="at">ref =</span> <span class="st">"Empleado_particular"</span>)</span>
<span id="cb5-45"><a href="#cb5-45" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-46"><a href="#cb5-46" aria-hidden="true" tabindex="-1"></a><span class="co"># --- Selección y limpieza final -------------------------------------------</span></span>
<span id="cb5-47"><a href="#cb5-47" aria-hidden="true" tabindex="-1"></a>datos_modelo <span class="ot">&lt;-</span> datos <span class="sc">%&gt;%</span></span>
<span id="cb5-48"><a href="#cb5-48" aria-hidden="true" tabindex="-1"></a>  <span class="fu">rename</span>(<span class="at">horas =</span> p6800, <span class="at">antiguedad =</span> p6426, <span class="at">ingreso =</span> inglabo, <span class="at">edad =</span> p6040) <span class="sc">%&gt;%</span></span>
<span id="cb5-49"><a href="#cb5-49" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(ingreso, ln_ingreso, horas, edad, escolaridad, experiencia, experiencia2,</span>
<span id="cb5-50"><a href="#cb5-50" aria-hidden="true" tabindex="-1"></a>         antiguedad, posicion, rama) <span class="sc">%&gt;%</span></span>
<span id="cb5-51"><a href="#cb5-51" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(<span class="fu">complete.cases</span>(.)) <span class="sc">%&gt;%</span></span>
<span id="cb5-52"><a href="#cb5-52" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(horas <span class="sc">&gt;</span> <span class="dv">0</span>, horas <span class="sc">&lt;=</span> <span class="dv">100</span>,</span>
<span id="cb5-53"><a href="#cb5-53" aria-hidden="true" tabindex="-1"></a>         escolaridad <span class="sc">&gt;=</span> <span class="dv">0</span>, escolaridad <span class="sc">&lt;=</span> <span class="dv">25</span>,</span>
<span id="cb5-54"><a href="#cb5-54" aria-hidden="true" tabindex="-1"></a>         antiguedad <span class="sc">&gt;=</span> <span class="dv">0</span>)</span>
<span id="cb5-55"><a href="#cb5-55" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-56"><a href="#cb5-56" aria-hidden="true" tabindex="-1"></a>poblacion_n <span class="ot">&lt;-</span> <span class="fu">nrow</span>(datos_modelo)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
</div>
<p>Tras la unión, la construcción de variables y la eliminación de registros incompletos o inconsistentes (horas fuera de rango, escolaridad fuera de rango, etc.), la base analítica de referencia queda con 27327 observaciones.</p>
</section>
<section id="selección-de-la-muestra" class="level2" data-number="3.2">
<h2 data-number="3.2" class="anchored" data-anchor-id="selección-de-la-muestra"><span class="header-section-number">3.2</span> Selección de la muestra</h2>
<p>Siguiendo la restricción del enunciado (máximo 100 registros), se aplicó un muestreo aleatorio simple (MAS) sobre la base analítica de referencia para obtener una muestra de <span class="math inline">\(n=100\)</span> observaciones. Bajo este esquema, cada individuo tuvo la misma probabilidad de selección:</p>
<p><span class="math display">\[\pi_i = \frac{n}{N} = \frac{100}{27327}\]</span></p>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb6"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">123</span>)</span>
<span id="cb6-2"><a href="#cb6-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-3"><a href="#cb6-3" aria-hidden="true" tabindex="-1"></a>n_muestra <span class="ot">&lt;-</span> <span class="dv">100</span></span>
<span id="cb6-4"><a href="#cb6-4" aria-hidden="true" tabindex="-1"></a>muestra <span class="ot">&lt;-</span> datos_modelo <span class="sc">%&gt;%</span> <span class="fu">slice_sample</span>(<span class="at">n =</span> n_muestra)</span>
<span id="cb6-5"><a href="#cb6-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-6"><a href="#cb6-6" aria-hidden="true" tabindex="-1"></a>fraccion_muestreo <span class="ot">&lt;-</span> <span class="fu">round</span>(n_muestra <span class="sc">/</span> poblacion_n <span class="sc">*</span> <span class="dv">100</span>, <span class="dv">2</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
</div>
<div class="cell">
<div class="cell-output-display">
<table class="caption-top table table-sm table-striped small">
<caption>Parámetros del muestreo aleatorio simple</caption>
<thead>
<tr class="header">
<th style="text-align: left;">Parametro</th>
<th style="text-align: left;">Valor</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Población de referencia (N)</td>
<td style="text-align: left;">27327</td>
</tr>
<tr class="even">
<td style="text-align: left;">Tamaño de muestra (n)</td>
<td style="text-align: left;">100</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Fracción de muestreo (n/N)</td>
<td style="text-align: left;">0.37%</td>
</tr>
<tr class="even">
<td style="text-align: left;">Semilla aleatoria</td>
<td style="text-align: left;">123</td>
</tr>
</tbody>
</table>
</div>
</div>
</section>
<section id="base-consolidada" class="level2" data-number="3.3">
<h2 data-number="3.3" class="anchored" data-anchor-id="base-consolidada"><span class="header-section-number">3.3</span> Base consolidada</h2>
<p>La base analítica final contiene 100 observaciones y 8 variables: la variable respuesta, cinco covariables continuas (horas, escolaridad, experiencia, experiencia al cuadrado y antigüedad) y dos variables categóricas (posición ocupacional y rama de actividad).</p>
<div class="cell">
<div class="cell-output-display">
<table class="caption-top table table-sm table-striped small">
<caption>Primeras diez observaciones de la base consolidada</caption>
<colgroup>
<col style="width: 12%">
<col style="width: 6%">
<col style="width: 13%">
<col style="width: 13%">
<col style="width: 14%">
<col style="width: 12%">
<col style="width: 22%">
<col style="width: 5%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: right;">ln_ingreso</th>
<th style="text-align: right;">horas</th>
<th style="text-align: right;">escolaridad</th>
<th style="text-align: right;">experiencia</th>
<th style="text-align: right;">experiencia2</th>
<th style="text-align: right;">antiguedad</th>
<th style="text-align: left;">posicion</th>
<th style="text-align: left;">rama</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: right;">14.60</td>
<td style="text-align: right;">50</td>
<td style="text-align: right;">11.0</td>
<td style="text-align: right;">28.0</td>
<td style="text-align: right;">784.00</td>
<td style="text-align: right;">288</td>
<td style="text-align: left;">Empleado_gobierno</td>
<td style="text-align: left;">84</td>
</tr>
<tr class="even">
<td style="text-align: right;">14.57</td>
<td style="text-align: right;">30</td>
<td style="text-align: right;">19.5</td>
<td style="text-align: right;">20.5</td>
<td style="text-align: right;">420.25</td>
<td style="text-align: right;">0</td>
<td style="text-align: left;">Empleado_particular</td>
<td style="text-align: left;">85</td>
</tr>
<tr class="odd">
<td style="text-align: right;">14.51</td>
<td style="text-align: right;">50</td>
<td style="text-align: right;">14.0</td>
<td style="text-align: right;">39.0</td>
<td style="text-align: right;">1521.00</td>
<td style="text-align: right;">480</td>
<td style="text-align: left;">Empleado_gobierno</td>
<td style="text-align: left;">86</td>
</tr>
<tr class="even">
<td style="text-align: right;">14.91</td>
<td style="text-align: right;">47</td>
<td style="text-align: right;">21.0</td>
<td style="text-align: right;">31.0</td>
<td style="text-align: right;">961.00</td>
<td style="text-align: right;">96</td>
<td style="text-align: left;">Empleado_gobierno</td>
<td style="text-align: left;">85</td>
</tr>
<tr class="odd">
<td style="text-align: right;">13.02</td>
<td style="text-align: right;">70</td>
<td style="text-align: right;">6.0</td>
<td style="text-align: right;">10.0</td>
<td style="text-align: right;">100.00</td>
<td style="text-align: right;">24</td>
<td style="text-align: left;">Cuenta_propia</td>
<td style="text-align: left;">92</td>
</tr>
<tr class="even">
<td style="text-align: right;">13.30</td>
<td style="text-align: right;">20</td>
<td style="text-align: right;">5.0</td>
<td style="text-align: right;">54.0</td>
<td style="text-align: right;">2916.00</td>
<td style="text-align: right;">3</td>
<td style="text-align: left;">Cuenta_propia</td>
<td style="text-align: left;">56</td>
</tr>
<tr class="odd">
<td style="text-align: right;">14.56</td>
<td style="text-align: right;">47</td>
<td style="text-align: right;">13.0</td>
<td style="text-align: right;">19.0</td>
<td style="text-align: right;">361.00</td>
<td style="text-align: right;">60</td>
<td style="text-align: left;">Empleado_gobierno</td>
<td style="text-align: left;">36</td>
</tr>
<tr class="even">
<td style="text-align: right;">13.82</td>
<td style="text-align: right;">50</td>
<td style="text-align: right;">11.0</td>
<td style="text-align: right;">21.0</td>
<td style="text-align: right;">441.00</td>
<td style="text-align: right;">8</td>
<td style="text-align: left;">Empleado_particular</td>
<td style="text-align: left;">47</td>
</tr>
<tr class="odd">
<td style="text-align: right;">13.65</td>
<td style="text-align: right;">48</td>
<td style="text-align: right;">4.0</td>
<td style="text-align: right;">49.0</td>
<td style="text-align: right;">2401.00</td>
<td style="text-align: right;">186</td>
<td style="text-align: left;">Cuenta_propia</td>
<td style="text-align: left;">81</td>
</tr>
<tr class="even">
<td style="text-align: right;">15.32</td>
<td style="text-align: right;">48</td>
<td style="text-align: right;">21.0</td>
<td style="text-align: right;">28.0</td>
<td style="text-align: right;">784.00</td>
<td style="text-align: right;">336</td>
<td style="text-align: left;">Empleado_particular</td>
<td style="text-align: left;">71</td>
</tr>
</tbody>
</table>
</div>
</div>
</section>
<section id="variable-respuesta-logaritmo-del-ingreso-laboral-mensual" class="level2" data-number="3.4">
<h2 data-number="3.4" class="anchored" data-anchor-id="variable-respuesta-logaritmo-del-ingreso-laboral-mensual"><span class="header-section-number">3.4</span> Variable respuesta: logaritmo del ingreso laboral mensual</h2>
<div class="cell">
<div class="cell-output-display">
<table class="caption-top table table-sm table-striped small">
<caption>Estadísticos descriptivos del logaritmo del ingreso laboral mensual</caption>
<thead>
<tr class="header">
<th style="text-align: left;">Medida</th>
<th style="text-align: left;">Valor</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">n</td>
<td style="text-align: left;">100</td>
</tr>
<tr class="even">
<td style="text-align: left;">Media</td>
<td style="text-align: left;">13.884</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Mediana</td>
<td style="text-align: left;">13.964</td>
</tr>
<tr class="even">
<td style="text-align: left;">Desviación estándar</td>
<td style="text-align: left;">0.735</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Coeficiente de variación</td>
<td style="text-align: left;">5.3%</td>
</tr>
<tr class="even">
<td style="text-align: left;">Mínimo</td>
<td style="text-align: left;">11.695</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Primer cuartil (Q1)</td>
<td style="text-align: left;">13.592</td>
</tr>
<tr class="even">
<td style="text-align: left;">Tercer cuartil (Q3)</td>
<td style="text-align: left;">14.221</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Máximo</td>
<td style="text-align: left;">15.607</td>
</tr>
<tr class="even">
<td style="text-align: left;">Asimetría</td>
<td style="text-align: left;">-0.625</td>
</tr>
</tbody>
</table>
</div>
</div>
<p>La Tabla anterior presenta los estadísticos descriptivos de la variable de respuesta ya transformada. En promedio, el log-ingreso de la muestra es de 13.884, con una mediana de 13.964; la cercanía entre ambas medidas y una asimetría de -0.625 son consistentes con el efecto esperado de la transformación logarítmica: corrige buena parte del sesgo positivo propio de la distribución original de los ingresos.</p>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="borrador_correcciones_corregido--8-_files/figure-html/hist-y-1.png" class="img-fluid figure-img" width="864"></p>
</figure>
</div>
</div>
</div>
<p>Se muestra el ingreso en su escala original y ya transformado a logaritmo: el histograma de la izquierda evidencia la asimetría positiva característica de los ingresos laborales (unos pocos valores muy altos alargan la cola derecha), mientras que el de la derecha muestra una distribución considerablemente más simétrica, lo que respalda el uso de <span class="math inline">\(\ln(Y)\)</span> como variable de respuesta del modelo.</p>
</section>
<section id="descripción-de-las-covariables-continuas" class="level2" data-number="3.5">
<h2 data-number="3.5" class="anchored" data-anchor-id="descripción-de-las-covariables-continuas"><span class="header-section-number">3.5</span> Descripción de las covariables continuas</h2>
<div class="cell">
<div class="cell-output-display">
<table class="caption-top table table-sm table-striped small">
<caption>Estadísticos descriptivos de las covariables continuas (n = 100)</caption>
<thead>
<tr class="header">
<th style="text-align: left;">Variable</th>
<th style="text-align: right;">Media</th>
<th style="text-align: right;">Mediana</th>
<th style="text-align: right;">DE</th>
<th style="text-align: right;">Min</th>
<th style="text-align: right;">Max</th>
<th style="text-align: right;">Q1</th>
<th style="text-align: right;">Q3</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">antiguedad</td>
<td style="text-align: right;">69.13</td>
<td style="text-align: right;">24.00</td>
<td style="text-align: right;">95.76</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">480.0</td>
<td style="text-align: right;">12.00</td>
<td style="text-align: right;">84.00</td>
</tr>
<tr class="even">
<td style="text-align: left;">escolaridad</td>
<td style="text-align: right;">11.72</td>
<td style="text-align: right;">11.00</td>
<td style="text-align: right;">5.93</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">23.5</td>
<td style="text-align: right;">7.75</td>
<td style="text-align: right;">14.50</td>
</tr>
<tr class="odd">
<td style="text-align: left;">experiencia</td>
<td style="text-align: right;">23.52</td>
<td style="text-align: right;">20.25</td>
<td style="text-align: right;">15.51</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">64.0</td>
<td style="text-align: right;">10.75</td>
<td style="text-align: right;">34.25</td>
</tr>
<tr class="even">
<td style="text-align: left;">experiencia2</td>
<td style="text-align: right;">790.98</td>
<td style="text-align: right;">410.12</td>
<td style="text-align: right;">905.15</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">4096.0</td>
<td style="text-align: right;">115.75</td>
<td style="text-align: right;">1173.25</td>
</tr>
<tr class="odd">
<td style="text-align: left;">horas</td>
<td style="text-align: right;">44.35</td>
<td style="text-align: right;">47.00</td>
<td style="text-align: right;">14.44</td>
<td style="text-align: right;">8</td>
<td style="text-align: right;">90.0</td>
<td style="text-align: right;">40.00</td>
<td style="text-align: right;">48.00</td>
</tr>
</tbody>
</table>
</div>
</div>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="borrador_correcciones_corregido--8-_files/figure-html/scatter-covariables-1.png" class="img-fluid figure-img" width="576"></p>
</figure>
</div>
</div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="borrador_correcciones_corregido--8-_files/figure-html/scatter-covariables-2.png" class="img-fluid figure-img" width="576"></p>
</figure>
</div>
</div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="borrador_correcciones_corregido--8-_files/figure-html/scatter-covariables-3.png" class="img-fluid figure-img" width="576"></p>
</figure>
</div>
</div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="borrador_correcciones_corregido--8-_files/figure-html/scatter-covariables-4.png" class="img-fluid figure-img" width="576"></p>
</figure>
</div>
</div>
</div>
<p>Las figuras anteriores muestran la relación entre el log-ingreso y cada covariable continua, junto con una curva LOESS y el coeficiente de correlación de Pearson. Conforme a la teoría del capital humano, se espera que la escolaridad y las horas trabajadas muestren las asociaciones positivas más claras; la relación con la experiencia potencial debería aproximarse a una forma cóncava, coherente con la inclusión de su término cuadrático en el modelo.</p>
<div class="cell">
<div class="cell-output-display">
<table class="caption-top table table-sm table-striped small">
<caption>Matriz de correlaciones de Pearson entre las variables continuas</caption>
<thead>
<tr class="header">
<th style="text-align: left;"></th>
<th style="text-align: right;">ln_ingreso</th>
<th style="text-align: right;">horas</th>
<th style="text-align: right;">escolaridad</th>
<th style="text-align: right;">experiencia</th>
<th style="text-align: right;">antiguedad</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">ln_ingreso</td>
<td style="text-align: right;">1.000</td>
<td style="text-align: right;">0.407</td>
<td style="text-align: right;">0.641</td>
<td style="text-align: right;">-0.226</td>
<td style="text-align: right;">0.283</td>
</tr>
<tr class="even">
<td style="text-align: left;">horas</td>
<td style="text-align: right;">0.407</td>
<td style="text-align: right;">1.000</td>
<td style="text-align: right;">0.109</td>
<td style="text-align: right;">-0.135</td>
<td style="text-align: right;">0.218</td>
</tr>
<tr class="odd">
<td style="text-align: left;">escolaridad</td>
<td style="text-align: right;">0.641</td>
<td style="text-align: right;">0.109</td>
<td style="text-align: right;">1.000</td>
<td style="text-align: right;">-0.447</td>
<td style="text-align: right;">0.176</td>
</tr>
<tr class="even">
<td style="text-align: left;">experiencia</td>
<td style="text-align: right;">-0.226</td>
<td style="text-align: right;">-0.135</td>
<td style="text-align: right;">-0.447</td>
<td style="text-align: right;">1.000</td>
<td style="text-align: right;">0.274</td>
</tr>
<tr class="odd">
<td style="text-align: left;">antiguedad</td>
<td style="text-align: right;">0.283</td>
<td style="text-align: right;">0.218</td>
<td style="text-align: right;">0.176</td>
<td style="text-align: right;">0.274</td>
<td style="text-align: right;">1.000</td>
</tr>
</tbody>
</table>
</div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="borrador_correcciones_corregido--8-_files/figure-html/matriz-correlacion-1.png" class="img-fluid figure-img" width="576"></p>
</figure>
</div>
</div>
</div>
<p>La matriz de correlaciones permite evaluar, además de la relación con la variable de respuesta, el grado de asociación entre las covariables entre sí — un primer indicio sobre posibles problemas de multicolinealidad que se evaluarán formalmente (VIF) en etapas posteriores del proyecto.</p>
</section>
<section id="descripción-de-las-variables-categóricas" class="level2" data-number="3.6">
<h2 data-number="3.6" class="anchored" data-anchor-id="descripción-de-las-variables-categóricas"><span class="header-section-number">3.6</span> Descripción de las variables categóricas</h2>
<section id="posición-ocupacional" class="level3" data-number="3.6.1">
<h3 data-number="3.6.1" class="anchored" data-anchor-id="posición-ocupacional"><span class="header-section-number">3.6.1</span> Posición ocupacional</h3>
<div class="cell">
<div class="cell-output-display">
<table class="caption-top table table-sm table-striped small">
<caption>Distribución de la muestra y log-ingreso medio según posición ocupacional (n = 100)</caption>
<colgroup>
<col style="width: 42%">
<col style="width: 4%">
<col style="width: 25%">
<col style="width: 27%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">posicion</th>
<th style="text-align: right;">n</th>
<th style="text-align: right;">Media_ln_ingreso</th>
<th style="text-align: right;">Mediana_ln_ingreso</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Empleado_particular</td>
<td style="text-align: right;">42</td>
<td style="text-align: right;">14.04</td>
<td style="text-align: right;">13.98</td>
</tr>
<tr class="even">
<td style="text-align: left;">Cuenta_propia</td>
<td style="text-align: right;">42</td>
<td style="text-align: right;">13.62</td>
<td style="text-align: right;">13.77</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Empleado_gobierno</td>
<td style="text-align: right;">8</td>
<td style="text-align: right;">14.78</td>
<td style="text-align: right;">14.76</td>
</tr>
<tr class="even">
<td style="text-align: left;">Empleado_domestico</td>
<td style="text-align: right;">5</td>
<td style="text-align: right;">13.05</td>
<td style="text-align: right;">13.42</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Trab_sin_remun_otros_hogares</td>
<td style="text-align: right;">2</td>
<td style="text-align: right;">14.04</td>
<td style="text-align: right;">14.04</td>
</tr>
<tr class="even">
<td style="text-align: left;">Patron_empleador</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">15.42</td>
<td style="text-align: right;">15.42</td>
</tr>
</tbody>
</table>
</div>
</div>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="borrador_correcciones_corregido--8-_files/figure-html/boxplot-posicion-1.png" class="img-fluid figure-img" width="768"></p>
</figure>
</div>
</div>
</div>
</section>
<section id="rama-de-actividad-económica" class="level3" data-number="3.6.2">
<h3 data-number="3.6.2" class="anchored" data-anchor-id="rama-de-actividad-económica"><span class="header-section-number">3.6.2</span> Rama de actividad económica</h3>
<div class="cell">
<div class="cell-output-display">
<table class="caption-top table table-sm table-striped small">
<caption>Distribución de la muestra y log-ingreso medio según rama de actividad (n = 100)</caption>
<thead>
<tr class="header">
<th style="text-align: left;">rama</th>
<th style="text-align: right;">n</th>
<th style="text-align: right;">Media_ln_ingreso</th>
<th style="text-align: right;">Mediana_ln_ingreso</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">47</td>
<td style="text-align: right;">15</td>
<td style="text-align: right;">13.62</td>
<td style="text-align: right;">13.82</td>
</tr>
<tr class="even">
<td style="text-align: left;">49</td>
<td style="text-align: right;">7</td>
<td style="text-align: right;">13.91</td>
<td style="text-align: right;">13.96</td>
</tr>
<tr class="odd">
<td style="text-align: left;">56</td>
<td style="text-align: right;">7</td>
<td style="text-align: right;">13.50</td>
<td style="text-align: right;">13.46</td>
</tr>
<tr class="even">
<td style="text-align: left;">85</td>
<td style="text-align: right;">7</td>
<td style="text-align: right;">14.74</td>
<td style="text-align: right;">14.73</td>
</tr>
<tr class="odd">
<td style="text-align: left;">01</td>
<td style="text-align: right;">5</td>
<td style="text-align: right;">14.11</td>
<td style="text-align: right;">14.00</td>
</tr>
<tr class="even">
<td style="text-align: left;">84</td>
<td style="text-align: right;">5</td>
<td style="text-align: right;">14.40</td>
<td style="text-align: right;">14.29</td>
</tr>
<tr class="odd">
<td style="text-align: left;">86</td>
<td style="text-align: right;">5</td>
<td style="text-align: right;">14.20</td>
<td style="text-align: right;">14.08</td>
</tr>
<tr class="even">
<td style="text-align: left;">96</td>
<td style="text-align: right;">5</td>
<td style="text-align: right;">13.73</td>
<td style="text-align: right;">13.59</td>
</tr>
<tr class="odd">
<td style="text-align: left;">97</td>
<td style="text-align: right;">5</td>
<td style="text-align: right;">13.05</td>
<td style="text-align: right;">13.42</td>
</tr>
<tr class="even">
<td style="text-align: left;">81</td>
<td style="text-align: right;">4</td>
<td style="text-align: right;">13.15</td>
<td style="text-align: right;">13.09</td>
</tr>
<tr class="odd">
<td style="text-align: left;">41</td>
<td style="text-align: right;">3</td>
<td style="text-align: right;">12.95</td>
<td style="text-align: right;">13.38</td>
</tr>
<tr class="even">
<td style="text-align: left;">14</td>
<td style="text-align: right;">2</td>
<td style="text-align: right;">14.00</td>
<td style="text-align: right;">14.00</td>
</tr>
<tr class="odd">
<td style="text-align: left;">23</td>
<td style="text-align: right;">2</td>
<td style="text-align: right;">14.07</td>
<td style="text-align: right;">14.07</td>
</tr>
<tr class="even">
<td style="text-align: left;">36</td>
<td style="text-align: right;">2</td>
<td style="text-align: right;">14.26</td>
<td style="text-align: right;">14.26</td>
</tr>
<tr class="odd">
<td style="text-align: left;">45</td>
<td style="text-align: right;">2</td>
<td style="text-align: right;">13.56</td>
<td style="text-align: right;">13.56</td>
</tr>
<tr class="even">
<td style="text-align: left;">46</td>
<td style="text-align: right;">2</td>
<td style="text-align: right;">14.33</td>
<td style="text-align: right;">14.33</td>
</tr>
<tr class="odd">
<td style="text-align: left;">64</td>
<td style="text-align: right;">2</td>
<td style="text-align: right;">13.71</td>
<td style="text-align: right;">13.71</td>
</tr>
<tr class="even">
<td style="text-align: left;">68</td>
<td style="text-align: right;">2</td>
<td style="text-align: right;">13.96</td>
<td style="text-align: right;">13.96</td>
</tr>
<tr class="odd">
<td style="text-align: left;">71</td>
<td style="text-align: right;">2</td>
<td style="text-align: right;">15.46</td>
<td style="text-align: right;">15.46</td>
</tr>
<tr class="even">
<td style="text-align: left;">95</td>
<td style="text-align: right;">2</td>
<td style="text-align: right;">13.97</td>
<td style="text-align: right;">13.97</td>
</tr>
<tr class="odd">
<td style="text-align: left;">20</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">13.96</td>
<td style="text-align: right;">13.96</td>
</tr>
<tr class="even">
<td style="text-align: left;">25</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">14.00</td>
<td style="text-align: right;">14.00</td>
</tr>
<tr class="odd">
<td style="text-align: left;">29</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">13.96</td>
<td style="text-align: right;">13.96</td>
</tr>
<tr class="even">
<td style="text-align: left;">31</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">13.30</td>
<td style="text-align: right;">13.30</td>
</tr>
<tr class="odd">
<td style="text-align: left;">35</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">14.05</td>
<td style="text-align: right;">14.05</td>
</tr>
<tr class="even">
<td style="text-align: left;">52</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">13.30</td>
<td style="text-align: right;">13.30</td>
</tr>
<tr class="odd">
<td style="text-align: left;">55</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">13.96</td>
<td style="text-align: right;">13.96</td>
</tr>
<tr class="even">
<td style="text-align: left;">65</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">14.08</td>
<td style="text-align: right;">14.08</td>
</tr>
<tr class="odd">
<td style="text-align: left;">66</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">14.73</td>
<td style="text-align: right;">14.73</td>
</tr>
<tr class="even">
<td style="text-align: left;">69</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">14.73</td>
<td style="text-align: right;">14.73</td>
</tr>
<tr class="odd">
<td style="text-align: left;">73</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">14.00</td>
<td style="text-align: right;">14.00</td>
</tr>
<tr class="even">
<td style="text-align: left;">80</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">14.40</td>
<td style="text-align: right;">14.40</td>
</tr>
<tr class="odd">
<td style="text-align: left;">82</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">13.96</td>
<td style="text-align: right;">13.96</td>
</tr>
<tr class="even">
<td style="text-align: left;">92</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">13.02</td>
<td style="text-align: right;">13.02</td>
</tr>
</tbody>
</table>
</div>
</div>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="borrador_correcciones_corregido--8-_files/figure-html/boxplot-rama-1.png" class="img-fluid figure-img" width="864"></p>
</figure>
</div>
</div>
</div>
<p>Al tratarse de una muestra de 100 observaciones, es esperable que algunas categorías —tanto de posición ocupacional como de rama de actividad— queden representadas por muy pocas observaciones. Esto deberá tenerse en cuenta al momento de estimar el modelo, evaluando si es necesario agrupar categorías poco frecuentes para evitar coeficientes poco confiables.</p>
</section>
</section>
</section>
<section id="modelo-matemático-propuesto" class="level1" data-number="4">
<h1 data-number="4"><span class="header-section-number">4</span> Modelo matemático propuesto</h1>
<p>Con fundamento en la teoría del capital humano y en la especificación clásica de la ecuación de ingresos de Mincer, se propone estimar un modelo de regresión lineal múltiple en el que el logaritmo natural del ingreso laboral mensual constituye la variable dependiente:</p>
<p><span class="math display">\[\ln(Y_i)=\beta_0+\beta_1X_{1i}+\beta_2X_{2i}
+\beta_3X_{3i}
+\beta_4X_{4i}
+\beta_5X_{5i}
+\beta_6X_{6i}
+\beta_7X_{7i}
+\varepsilon_i\]</span></p>
<p>donde <span class="math inline">\(X_1\)</span>: horas trabajadas por semana; <span class="math inline">\(X_2\)</span>: años de escolaridad; <span class="math inline">\(X_3\)</span>: experiencia potencial; <span class="math inline">\(X_4\)</span>: experiencia potencial al cuadrado; <span class="math inline">\(X_5\)</span>: posición ocupacional (dummy); <span class="math inline">\(X_6\)</span>: antigüedad en el empleo actual; <span class="math inline">\(X_7\)</span>: rama de actividad económica (dummy); <span class="math inline">\(\beta_0\)</span>: intercepto; <span class="math inline">\(\varepsilon_i\)</span>: error aleatorio.</p>
<p>Antes de estimar el modelo definitivo se verificará el cumplimiento de los supuestos de la regresión lineal múltiple, evaluando la existencia de multicolinealidad mediante el Factor de Inflación de la Varianza (VIF), la homocedasticidad de los residuos, la normalidad de los errores y la posible presencia de observaciones influyentes.</p>
</section>
<section id="conclusiones" class="level1" data-number="5">
<h1 data-number="5"><span class="header-section-number">5</span> Conclusiones</h1>
<p>El análisis descriptivo confirma que la transformación logarítmica del ingreso laboral corrige de forma considerable la asimetría propia de esta variable, lo que respalda su uso como variable de respuesta del modelo. Las covariables continuas —en particular escolaridad y horas trabajadas— muestran las asociaciones esperadas con el log-ingreso según la teoría del capital humano, mientras que la posición ocupacional y la rama de actividad evidencian diferencias en el nivel medio de ingreso entre categorías, lo que sugiere que ambas variables aportan información relevante para el modelo más allá de la escolaridad y la experiencia.</p>
<p>Al mismo tiempo, el análisis muestra que ninguna covariable por sí sola explica la totalidad de la variabilidad del ingreso, lo que anticipa que sus efectos deberán evaluarse de forma conjunta en un modelo de regresión múltiple, prestando especial atención a la multicolinealidad entre escolaridad y experiencia (ambas derivadas de la edad y el nivel educativo) y a las categorías con pocas observaciones dentro de posición ocupacional y rama de actividad.</p>
</section>
<section id="referencias" class="level1" data-number="6">
<h1 data-number="6"><span class="header-section-number">6</span> Referencias</h1>
<p>Mincer, J. (1974). <em>Schooling, Experience, and Earnings</em>. National Bureau of Economic Research.</p>
<p>Departamento Administrativo Nacional de Estadística – DANE. (2024). <em>Gran Encuesta Integrada de Hogares (GEIH)</em>. Microdatos. Recuperado de https://microdatos.dane.gov.co</p>
</section>

</main>
<!-- /main column -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp('/' + window.location.host + '/');
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
</div> <!-- /content -->




</body></html>